package alignmentparser;

import java.util.ArrayList;
import java.util.HashMap;

public class AminoAcidMap {
	public static HashMap<String, ArrayList<String>> assembleMap() {
		ArrayList<String> ala = new ArrayList<String>();
	    ala.add("GCT");
	    ala.add("GCC");
	    ala.add("GCA");
	    ala.add("GCG");
	    ArrayList<String> arg = new ArrayList<String>();
	    arg.add("CGT");
	    arg.add("CGC");
	    arg.add("CGA");
	    arg.add("CGG");
	    arg.add("AGA");
	    arg.add("AGG");
	    ArrayList<String> asn = new ArrayList<String>();
	    asn.add("AAT");
	    asn.add("AAC");
	    ArrayList<String> asp = new ArrayList<String>();
	    asp.add("GAT");
	    asp.add("GAC");
	    ArrayList<String> cys = new ArrayList<String>();
	    cys.add("TGT");
	    cys.add("TGC");
	    ArrayList<String> gln = new ArrayList<String>();
	    gln.add("CAA");
	    gln.add("CAG");
	    ArrayList<String> glu = new ArrayList<String>();
	    glu.add("GAA");
	    glu.add("GAG");
	    ArrayList<String> gly = new ArrayList<String>();
	    gly.add("GGT");
	    gly.add("GGC");
	    gly.add("GGA");
	    gly.add("GGG");
	    ArrayList<String> his = new ArrayList<String>();
	    his.add("CAT");
	    his.add("CAC");
	    ArrayList<String> ile = new ArrayList<String>();
	    ile.add("ATT");
	    ile.add("ATC");
	    ile.add("ATA");
	    ArrayList<String> leu = new ArrayList<String>();
	    leu.add("TTA");
	    leu.add("TTG");
	    leu.add("CTT");
	    leu.add("CTC");
	    leu.add("CTA");
	    leu.add("CTG");
	    ArrayList<String> lys = new ArrayList<String>();
	    lys.add("AAA");
	    lys.add("AAG");
	    ArrayList<String> met = new ArrayList<String>();
	    met.add("ATG");
	    ArrayList<String> phe = new ArrayList<String>();
	    phe.add("TTT");
	    phe.add("TTC");
	    ArrayList<String> pro = new ArrayList<String>();
	    pro.add("CCT");
	    pro.add("CCC");
	    pro.add("CCA");
	    pro.add("CCG");
	    ArrayList<String> ser = new ArrayList<String>();
	    ser.add("TCT");
	    ser.add("TCC");
	    ser.add("TCA");
	    ser.add("TCG");
	    ser.add("AGT");
	    ser.add("AGC");
	    ArrayList<String> thr = new ArrayList<String>();
	    thr.add("ACT");
	    thr.add("ACC");
	    thr.add("ACA");
	    thr.add("ACG");
	    ArrayList<String> trp = new ArrayList<String>();
	    trp.add("TGG");
	    ArrayList<String> tyr = new ArrayList<String>();
	    tyr.add("TAT");
	    tyr.add("TAC");
	    ArrayList<String> val = new ArrayList<String>();
	    val.add("GTT");
	    val.add("GTC");
	    val.add("GTA");
	    val.add("GTG");

	    HashMap<String, ArrayList<String>> map = new HashMap<String, ArrayList<String>>();
	    map.put("A", ala);
	    map.put("R", arg);
	    map.put("N", asn);
	    map.put("D", asp);
	    map.put("C", cys);
	    map.put("Q", gln);
	    map.put("E", glu);
	    map.put("G", gly);
	    map.put("H", his);
	    map.put("I", ile);
	    map.put("L", leu);
	    map.put("K", lys);
	    map.put("M", met);
	    map.put("F", phe);
	    map.put("P", pro);
	    map.put("S", ser);
	    map.put("T", thr);
	    map.put("W", trp);
	    map.put("Y", tyr);
	    map.put("V", val);
	    
	    return map;
	}
}
